Work on test code quality
No change of the test ouput but test realisation.
The tests are now independent (no workspace creation in constructor, workspace deletion at the end).
The private helper methods createUniformWorkspace and doGroupWorkspace are used now everywhere.
This means that they do not need to return a workspace pointer.
One test added that tests these helper methods in terms if workspaces are correctly put in ADS and deleted when desired.

The test output is (now with 26 tests)

ctest -R Stitch1DManyTest --output-on-failure
Test project /users/reimund/mantid
    Start 1236: AlgorithmsTest_Stitch1DManyTest
1/1 Test #1236: AlgorithmsTest_Stitch1DManyTest ...***Failed    6.21 sec
Running 25 tests.Stitch1DMany-[Warning] Invalid value for InputWorkspaces: At least 2 input workspaces required.
.Stitch1DMany-[Warning] Invalid value for EndOverlaps: EndOverlaps must have the same number of entries as StartOverlaps.
Stitch1DMany-[Warning] Invalid value for StartOverlaps: If given, StartOverlaps must have one fewer entries than the number of input workspaces.
.Stitch1DMany-[Warning] Invalid value for EndOverlaps: EndOverlaps must have the same number of entries as StartOverlaps.
.Stitch1DMany-[Warning] Invalid value for ManualScaleFactors: If given, ManualScaleFactors must either consist of one entry or one fewer entries than the number of input workspaces
.Stitch1DMany-[Warning] Invalid value for InputWorkspaces: Input workspaces must either be matrix workspaces or group workspaces containing matrix workspaces only
.Stitch1DMany-[Warning] Invalid value for InputWorkspaces: Input workspaces must either be matrix workspaces or group workspaces containing matrix workspaces only
.Stitch1DMany-[Warning] Invalid value for InputWorkspaces: Input workspaces must either be matrix workspaces or group workspaces containing matrix workspaces only
.Stitch1DMany-[Warning] Invalid value for InputWorkspaces: All workspace groups must be the same size.
.Stitch1DMany-[Warning] Invalid value for ScaleFactorFromPeriod: Period index out of range
.Stitch1D-[Warning] StartOverlap is outside range at 0.8000, Min is 0.8000, Max is 1.1000 . Forced to be: 0.8000
Stitch1D-[Warning] EndOverlap is outside range at 1.1000, Min is 0.8000, Max is 1.1000 . Forced to be: 1.1000
Stitch1D-[Notice] Scale Factor Y is: 0.909091 Scale Factor E is: 0.725204
Stitch1D-[Warning] StartOverlap is outside range at 0.8000, Min is 0.8000, Max is 1.1000 . Forced to be: 0.8000
Stitch1D-[Warning] EndOverlap is outside range at 1.1000, Min is 0.8000, Max is 1.1000 . Forced to be: 1.1000
Stitch1D-[Notice] Scale Factor Y is: 0.909091 Scale Factor E is: 0.725204
.Stitch1D-[Warning] StartOverlap is outside range at 0.8000, Min is 0.8000, Max is 1.1000 . Forced to be: 0.8000
Stitch1D-[Warning] EndOverlap is outside range at 1.1000, Min is 0.8000, Max is 1.1000 . Forced to be: 1.1000
Stitch1D-[Notice] Scale Factor Y is: 0.909091 Scale Factor E is: 0.725204
Stitch1D-[Warning] StartOverlap is outside range at 1.6000, Min is 1.6000, Max is 2.6000 . Forced to be: 1.6000
Stitch1D-[Notice] Scale Factor Y is: 0.666667 Scale Factor E is: 0.701129
.Stitch1D-[Notice] Scale Factor Y is: 0.909091 Scale Factor E is: 0.725204
Stitch1D-[Notice] Scale Factor Y is: 0.133333 Scale Factor E is: 0.122158
.Stitch1D-[Warning] StartOverlap is outside range at 0.8000, Min is 0.8000, Max is 1.1000 . Forced to be: 0.8000
Stitch1D-[Warning] EndOverlap is outside range at 1.1000, Min is 0.8000, Max is 1.1000 . Forced to be: 1.1000
Stitch1D-[Notice] Scale Factor Y is: 0.5 Scale Factor E is: 0.5
Stitch1D-[Warning] StartOverlap is outside range at 1.6000, Min is 1.6000, Max is 2.6000 . Forced to be: 1.6000
Stitch1D-[Notice] Scale Factor Y is: 0.5 Scale Factor E is: 0.5
.Stitch1D-[Warning] StartOverlap is outside range at 0.8000, Min is 0.8000, Max is 1.1000 . Forced to be: 0.8000
Stitch1D-[Warning] EndOverlap is outside range at 1.1000, Min is 0.8000, Max is 1.1000 . Forced to be: 1.1000
Stitch1D-[Notice] Scale Factor Y is: 0.5 Scale Factor E is: 0.5
Stitch1D-[Warning] StartOverlap is outside range at 1.6000, Min is 1.6000, Max is 2.6000 . Forced to be: 1.6000
Stitch1D-[Notice] Scale Factor Y is: 0.7 Scale Factor E is: 0.7
.Stitch1DMany-[Notice] Stitch1DMany started
Stitch1DMany-[Warning] Invalid value for InputWorkspaces: At least 2 input workspaces required.
Stitch1DMany-[Warning] Invalid value for StartOverlaps: If given, StartOverlaps must have one fewer entries than the number of input workspaces.
.Stitch1DMany-[Notice] Stitch1DMany started
Stitch1D-[Warning] StartOverlap is outside range at 0.8000, Min is 0.8000, Max is 1.1000 . Forced to be: 0.8000
Stitch1D-[Warning] EndOverlap is outside range at 1.1000, Min is 0.8000, Max is 1.1000 . Forced to be: 1.1000
Stitch1D-[Notice] Scale Factor Y is: 0.909091 Scale Factor E is: 0.725204
Stitch1D-[Warning] StartOverlap is outside range at 1.6000, Min is 1.6000, Max is 2.6000 . Forced to be: 1.6000
Stitch1D-[Notice] Scale Factor Y is: 0.666667 Scale Factor E is: 0.701129
Stitch1DMany-[Notice] Stitch1DMany successful, Duration 0.14 seconds
GroupWorkspaces-[Notice] GroupWorkspaces started (child)
GroupWorkspaces-[Notice] GroupWorkspaces successful, Duration 0.00 seconds
.Stitch1DMany-[Notice] Stitch1DMany started
Stitch1D-[Warning] StartOverlap is outside range at 0.8000, Min is 0.8000, Max is 1.1000 . Forced to be: 0.8000
Stitch1D-[Warning] EndOverlap is outside range at 1.1000, Min is 0.8000, Max is 1.1000 . Forced to be: 1.1000
Stitch1D-[Notice] Scale Factor Y is: 0.909091 Scale Factor E is: 0.725204
Stitch1DMany-[Notice] Stitch1DMany successful, Duration 0.01 seconds
Stitch1DMany-[Notice] Stitch1DMany started
Stitch1D-[Warning] StartOverlap is outside range at 0.8000, Min is 0.8000, Max is 1.1000 . Forced to be: 0.8000
Stitch1D-[Warning] EndOverlap is outside range at 1.1000, Min is 0.8000, Max is 1.1000 . Forced to be: 1.1000
Stitch1D-[Notice] Scale Factor Y is: 0.9375 Scale Factor E is: 0.615157
Stitch1DMany-[Notice] Stitch1DMany successful, Duration 0.01 seconds
GroupWorkspaces-[Notice] GroupWorkspaces started (child)
GroupWorkspaces-[Notice] GroupWorkspaces successful, Duration 0.00 seconds
.Stitch1DMany-[Notice] Stitch1DMany started
Stitch1D-[Warning] StartOverlap is outside range at 0.8000, Min is 0.8000, Max is 1.1000 . Forced to be: 0.8000
Stitch1D-[Warning] EndOverlap is outside range at 1.1000, Min is 0.8000, Max is 1.1000 . Forced to be: 1.1000
Stitch1D-[Notice] Scale Factor Y is: 0.5 Scale Factor E is: 0.5
Stitch1DMany-[Notice] Stitch1DMany successful, Duration 0.01 seconds
Stitch1DMany-[Notice] Stitch1DMany started
Stitch1D-[Warning] StartOverlap is outside range at 0.8000, Min is 0.8000, Max is 1.1000 . Forced to be: 0.8000
Stitch1D-[Warning] EndOverlap is outside range at 1.1000, Min is 0.8000, Max is 1.1000 . Forced to be: 1.1000
Stitch1D-[Notice] Scale Factor Y is: 0.5 Scale Factor E is: 0.5
Stitch1DMany-[Notice] Stitch1DMany successful, Duration 0.01 seconds
GroupWorkspaces-[Notice] GroupWorkspaces started (child)
GroupWorkspaces-[Notice] GroupWorkspaces successful, Duration 0.00 seconds
.Stitch1DMany-[Notice] Stitch1DMany started
Stitch1D-[Warning] StartOverlap is outside range at 0.8000, Min is 0.8000, Max is 1.1000 . Forced to be: 0.8000
Stitch1D-[Warning] EndOverlap is outside range at 1.1000, Min is 0.8000, Max is 1.1000 . Forced to be: 1.1000
Stitch1D-[Notice] Scale Factor Y is: 0.5 Scale Factor E is: 0.5
Stitch1D-[Warning] StartOverlap is outside range at 1.6000, Min is 1.6000, Max is 2.6000 . Forced to be: 1.6000
Stitch1D-[Notice] Scale Factor Y is: 0.7 Scale Factor E is: 0.7
Stitch1DMany-[Notice] Stitch1DMany successful, Duration 0.03 seconds
Stitch1DMany-[Notice] Stitch1DMany started
Stitch1D-[Warning] StartOverlap is outside range at 0.8000, Min is 0.8000, Max is 1.1000 . Forced to be: 0.8000
Stitch1D-[Warning] EndOverlap is outside range at 1.1000, Min is 0.8000, Max is 1.1000 . Forced to be: 1.1000
Stitch1D-[Notice] Scale Factor Y is: 0.5 Scale Factor E is: 0.5
Stitch1D-[Warning] StartOverlap is outside range at 1.6000, Min is 1.6000, Max is 2.6000 . Forced to be: 1.6000
Stitch1D-[Notice] Scale Factor Y is: 0.7 Scale Factor E is: 0.7
Stitch1DMany-[Notice] Stitch1DMany successful, Duration 0.06 seconds
GroupWorkspaces-[Notice] GroupWorkspaces started (child)
GroupWorkspaces-[Notice] GroupWorkspaces successful, Duration 0.00 seconds
.Stitch1DMany-[Notice] Stitch1DMany started
Stitch1D-[Warning] StartOverlap is outside range at 0.8000, Min is 0.8000, Max is 1.1000 . Forced to be: 0.8000
Stitch1D-[Warning] EndOverlap is outside range at 1.1000, Min is 0.8000, Max is 1.1000 . Forced to be: 1.1000
Stitch1D-[Notice] Scale Factor Y is: 0.9375 Scale Factor E is: 0.615157
Stitch1D-[Warning] StartOverlap is outside range at 1.6000, Min is 1.6000, Max is 2.6000 . Forced to be: 1.6000
Stitch1D-[Notice] Scale Factor Y is: 0.625 Scale Factor E is: 0.536231
Stitch1DMany-[Notice] Stitch1DMany successful, Duration 0.03 seconds
Stitch1D-[Warning] StartOverlap is outside range at 0.8000, Min is 0.8000, Max is 1.1000 . Forced to be: 0.8000
Stitch1D-[Warning] EndOverlap is outside range at 1.1000, Min is 0.8000, Max is 1.1000 . Forced to be: 1.1000
Stitch1D-[Notice] Scale Factor Y is: 0.9375 Scale Factor E is: 0.9375
Stitch1D-[Warning] StartOverlap is outside range at 1.6000, Min is 1.6000, Max is 2.6000 . Forced to be: 1.6000
Stitch1D-[Notice] Scale Factor Y is: 0.625 Scale Factor E is: 0.625
Stitch1D-[Warning] StartOverlap is outside range at 0.8000, Min is 0.8000, Max is 1.1000 . Forced to be: 0.8000
Stitch1D-[Warning] EndOverlap is outside range at 1.1000, Min is 0.8000, Max is 1.1000 . Forced to be: 1.1000
Stitch1D-[Notice] Scale Factor Y is: 0.9375 Scale Factor E is: 0.9375
Stitch1D-[Warning] StartOverlap is outside range at 1.6000, Min is 1.6000, Max is 2.6000 . Forced to be: 1.6000
Stitch1D-[Notice] Scale Factor Y is: 0.625 Scale Factor E is: 0.625
GroupWorkspaces-[Notice] GroupWorkspaces started (child)
GroupWorkspaces-[Notice] GroupWorkspaces successful, Duration 0.00 seconds
.CreateWorkspace-[Notice] CreateWorkspace started
CreateWorkspace-[Notice] CreateWorkspace successful, Duration 0.00 seconds
CreateWorkspace-[Notice] CreateWorkspace started
CreateWorkspace-[Notice] CreateWorkspace successful, Duration 0.00 seconds
Stitch1DMany-[Notice] Stitch1DMany started
Stitch1D-[Warning] StartOverlap is outside range at 0.8000, Min is 0.8000, Max is 1.1000 . Forced to be: 0.8000
Stitch1D-[Warning] EndOverlap is outside range at 1.1000, Min is 0.8000, Max is 1.1000 . Forced to be: 1.1000
Stitch1D-[Notice] Scale Factor Y is: 0.909091 Scale Factor E is: 0.725204
Stitch1DMany-[Notice] Stitch1DMany successful, Duration 0.01 seconds

In Stitch1DManyTest::test_two_workspaces_history:
/home/cs/reimund/mantid/Framework/Algorithms/test/Stitch1DManyTest.h:1122: Error: Assertion failed: outws
CreateWorkspace-[Notice] CreateWorkspace started
CreateWorkspace-[Notice] CreateWorkspace successful, Duration 0.00 seconds
CreateWorkspace-[Notice] CreateWorkspace started
CreateWorkspace-[Notice] CreateWorkspace successful, Duration 0.00 seconds
GroupWorkspaces-[Notice] GroupWorkspaces started
GroupWorkspaces-[Notice] GroupWorkspaces successful, Duration 0.00 seconds
CreateWorkspace-[Notice] CreateWorkspace started
CreateWorkspace-[Notice] CreateWorkspace successful, Duration 0.00 seconds
CreateWorkspace-[Notice] CreateWorkspace started
CreateWorkspace-[Notice] CreateWorkspace successful, Duration 0.00 seconds
GroupWorkspaces-[Notice] GroupWorkspaces started
GroupWorkspaces-[Notice] GroupWorkspaces successful, Duration 0.00 seconds
Stitch1DMany-[Notice] Stitch1DMany started
Stitch1DMany-[Notice] Stitch1DMany started
Stitch1D-[Warning] StartOverlap is outside range at 0.8000, Min is 0.8000, Max is 1.1000 . Forced to be: 0.8000
Stitch1D-[Warning] EndOverlap is outside range at 1.1000, Min is 0.8000, Max is 1.1000 . Forced to be: 1.1000
Stitch1D-[Notice] Scale Factor Y is: 0.909091 Scale Factor E is: 0.725204
Stitch1DMany-[Notice] Stitch1DMany successful, Duration 0.01 seconds
Stitch1DMany-[Notice] Stitch1DMany started
Stitch1D-[Warning] StartOverlap is outside range at 0.8000, Min is 0.8000, Max is 1.1000 . Forced to be: 0.8000
Stitch1D-[Warning] EndOverlap is outside range at 1.1000, Min is 0.8000, Max is 1.1000 . Forced to be: 1.1000
Stitch1D-[Notice] Scale Factor Y is: 0.9375 Scale Factor E is: 0.615157
Stitch1DMany-[Notice] Stitch1DMany successful, Duration 0.01 seconds
GroupWorkspaces-[Notice] GroupWorkspaces started (child)
GroupWorkspaces-[Notice] GroupWorkspaces successful, Duration 0.00 seconds
Stitch1DMany-[Notice] Stitch1DMany successful, Duration 0.03 seconds. Processed as a workspace group
In Stitch1DManyTest::test_two_groups_history:
/home/cs/reimund/mantid/Framework/Algorithms/test/Stitch1DManyTest.h:1172: Error: Assertion failed: outws
CreateWorkspace-[Notice] CreateWorkspace started
CreateWorkspace-[Notice] CreateWorkspace successful, Duration 0.00 seconds
CreateWorkspace-[Notice] CreateWorkspace started
CreateWorkspace-[Notice] CreateWorkspace successful, Duration 0.00 seconds
GroupWorkspaces-[Notice] GroupWorkspaces started
GroupWorkspaces-[Notice] GroupWorkspaces successful, Duration 0.00 seconds
CreateWorkspace-[Notice] CreateWorkspace started
CreateWorkspace-[Notice] CreateWorkspace successful, Duration 0.00 seconds
CreateWorkspace-[Notice] CreateWorkspace started
CreateWorkspace-[Notice] CreateWorkspace successful, Duration 0.00 seconds
GroupWorkspaces-[Notice] GroupWorkspaces started
GroupWorkspaces-[Notice] GroupWorkspaces successful, Duration 0.00 seconds
CreateWorkspace-[Notice] CreateWorkspace started
CreateWorkspace-[Notice] CreateWorkspace successful, Duration 0.00 seconds
CreateWorkspace-[Notice] CreateWorkspace started
CreateWorkspace-[Notice] CreateWorkspace successful, Duration 0.00 seconds
GroupWorkspaces-[Notice] GroupWorkspaces started
GroupWorkspaces-[Notice] GroupWorkspaces successful, Duration 0.00 seconds
Stitch1DMany-[Notice] Stitch1DMany started
Stitch1DMany-[Notice] Stitch1DMany started
Stitch1D-[Warning] StartOverlap is outside range at 0.8000, Min is 0.8000, Max is 1.1000 . Forced to be: 0.8000
Stitch1D-[Warning] EndOverlap is outside range at 1.1000, Min is 0.8000, Max is 1.1000 . Forced to be: 1.1000
Stitch1D-[Notice] Scale Factor Y is: 0.9375 Scale Factor E is: 0.615157
Stitch1D-[Warning] StartOverlap is outside range at 1.6000, Min is 1.6000, Max is 2.6000 . Forced to be: 1.6000
Stitch1D-[Notice] Scale Factor Y is: 0.625 Scale Factor E is: 0.536231
Stitch1DMany-[Notice] Stitch1DMany successful, Duration 0.03 seconds
Stitch1D-[Warning] StartOverlap is outside range at 0.8000, Min is 0.8000, Max is 1.1000 . Forced to be: 0.8000
Stitch1D-[Warning] EndOverlap is outside range at 1.1000, Min is 0.8000, Max is 1.1000 . Forced to be: 1.1000
Stitch1D-[Notice] Scale Factor Y is: 0.9375 Scale Factor E is: 0.9375
Stitch1D-[Warning] StartOverlap is outside range at 1.6000, Min is 1.6000, Max is 2.6000 . Forced to be: 1.6000
Stitch1D-[Notice] Scale Factor Y is: 0.625 Scale Factor E is: 0.625
Stitch1D-[Warning] StartOverlap is outside range at 0.8000, Min is 0.8000, Max is 1.1000 . Forced to be: 0.8000
Stitch1D-[Warning] EndOverlap is outside range at 1.1000, Min is 0.8000, Max is 1.1000 . Forced to be: 1.1000
Stitch1D-[Notice] Scale Factor Y is: 0.9375 Scale Factor E is: 0.9375
Stitch1D-[Warning] StartOverlap is outside range at 1.6000, Min is 1.6000, Max is 2.6000 . Forced to be: 1.6000
Stitch1D-[Notice] Scale Factor Y is: 0.625 Scale Factor E is: 0.625
GroupWorkspaces-[Notice] GroupWorkspaces started (child)
GroupWorkspaces-[Notice] GroupWorkspaces successful, Duration 0.00 seconds
Stitch1DMany-[Notice] Stitch1DMany successful, Duration 0.07 seconds. Processed as a workspace group
In Stitch1DManyTest::test_two_groups_scale_factor_from_period_history:
/home/cs/reimund/mantid/Framework/Algorithms/test/Stitch1DManyTest.h:1236: Error: Assertion failed: outws
.
Failed 3 of 25 tests
Success rate: 88%

Refs #22197