Pin pyzmq for macOS packaging
The dylibs released by version 21.0.0 seem to have set the minimum
deployment target to 10.15. On importing on a machine with
macOS <10.15 we get an error:
File "/Applications/MantidWorkbenchNightly.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (
ImportError: dlopen(/Applications/MantidWorkbenchNightly.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/zmq/backend/cython/constants.cpython-38-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/MantidWorkbenchNightly.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/zmq/backend/cython/../../.dylibs/libsodium.23.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/MantidWorkbenchNightly.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/zmq/backend/cython/../../.dylibs/libsodium.23.dylib

Pin to old pyzmq while we investigate