Revert "Replace block-style progress reporter with C-api based one"
This reverts commit f35671a7bb6c5a4312a8116bce8f8364f439167f.

Nightly failing to launch due to:
ModuleNotFoundError: No module name 'mantidqt.widgets._commonqt5'
when using packaged versions (cpack or nightly)