Introduce a temporary_directory system test method
It creates a temporary directory and registers a cleanUp
method with unittest
The HFIR tests now use this to create a temporary work
area, avoiding race conditions when tests run in parallel
and multiple cleanup functions tried to remove the same
file at the same time, with errors such as:

  File "C:/Jenkins/workspace/main_systemtests-windows/Testing/SystemTests/tests/framework\HFIRReductionAPIv2.py", line 25, in do_cleanup

    os.remove(absfile)

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Jenkins\\workspace\\main_systemtests-windows\\build\\ExternalData\\Testing\\Data\\SystemTest\\BioSANS_test_data_Iqxy.dat'