Revert "Add GitHub Actions workflow for Linux build and test PR check (#41018)"
This reverts commit 2c2644a6b3a06ec5796a78c9a5680ad0a4772fa6. It was
marking all PRs as having an issue with the error:

 Error: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node24' is not supported, use 'docker', 'node12', 'node16' or 'node20' instead.')

 taken from https://github.com/mantidproject/mantid/actions/runs/23057923666/job/66976405999?pr=41058