Avoid documentation warning, unrelated change
Noticed on master when making docs-qthelp:

Stitch1D-v3.rst:...: WARNING: Exception occurred in plotting Stitch1D-v3-2
 from Stitch1D-v3.rst:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/matplotlib/sphinxext/plot_directive.py", line 517, in run_code
    six.exec_(code, ns)
  File "/usr/lib/python2.7/dist-packages/matplotlib/externals/six.py", line 672, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "<string>", line 4, in <module>
  File "/users/reimund/mantid/bin/mantid/simpleapi.py", line 165, in Load
    'description: ' + str(ve) + '\nIf the file has been found '
ValueError: Problem when setting Filename. This is the detailed error description: Invalid value for property Filename (list of str lists) "INTER00013463": Unable to find file matching the string "INTER00013463", even after appending suggested file extensions.
If the file has been found but you got this error, you might not have read permissions or the file might be corrupted.
If the file has not been found, you might have forgotten to add its location in the data search directories.
looking for now-outdated files... none found

Data are not in usage data. Thus, message not added (.. include:: ../usagedata-note.txt).

Refs #22197