Fix NX5SIGNATURE error (#39582)
### Description of work

#### Summary of work

The value `NX5SIGNATURE` is used inside the Nexus/napi package to ensure
a file is an HDF5 file.

This needed to be moved to a more visible location.

Refs #38332 

Fixes a user-reported error due to NX5SIGNATURE on Windows, in [Mantid
slack
channel](https://mantid.slack.com/archives/C45NYR1BM/p1750856031711669).

#### Further detail of work
<!-- Please provide a more detailed description of the work that has
been undertaken.
-->

### To test:

Build this branch on Windows. IThe build servers are not sufficient,
because for some reason this passes there.

It is probably sufficient to build the `Nexus` target instead of the
entire program.

If this did NOT work, there will be an error 
```
5>C:\Users\kcd17618\Documents\dev\mantid\mantid\Framework\Nexus\src\napi_helper.cpp(14,3): error C2065: 'NX5SIGNATURE': undeclared identifier
5>Done building project "Nexus.vcxproj" -- FAILED.
```

If this DID work, there will be no error.

---

### Reviewer

Please comment on the points listed below ([full
description](http://developer.mantidproject.org/ReviewingAPullRequest.html)).
**Your comments will be used as part of the gatekeeper process, so
please comment clearly on what you have checked during your review.** If
changes are made to the PR during the review process then your final
comment will be the most important for gatekeepers. In this comment you
should make it clear why any earlier review is still valid, or confirm
that all requested changes have been addressed.

#### Code Review

- Is the code of an acceptable quality?
- Does the code conform to the [coding
standards](http://developer.mantidproject.org/Standards/)?
- Are the unit tests small and test the class in isolation?
- If there is GUI work does it follow the [GUI
standards](http://developer.mantidproject.org/Standards/GUIStandards.html)?
- If there are changes in the release notes then do they describe the
changes appropriately?
- Do the release notes conform to the [release notes
guide](https://developer.mantidproject.org/Standards/ReleaseNotesGuide.html)?

#### Functional Tests

- Do changes function as described? Add comments below that describe the
tests performed?
- Do the changes handle unexpected situations, e.g. bad input?
- Has the relevant (user and developer) documentation been
added/updated?

Does everything look good? Mark the review as **Approve**. A member of
`@mantidproject/gatekeepers` will take care of it.

### Gatekeeper

If you need to request changes to a PR then please add a comment and set
the review status to "Request changes". This will stop the PR from
showing up in the list for other gatekeepers.