Revert "Re #0. Use clamp in DateAndTime."
This reverts commit 480f7776446b6e93e9d34c9c9b6d0db24d05406b.

Issues on clang:
07:12:15 Undefined symbols for architecture x86_64:
07:12:15   "Mantid::Types::Core::DateAndTime::MAX_NANOSECONDS",
referenced from:
07:12:15       Mantid::Types::Core::DateAndTime::maximum() in
DateAndTime.cpp.o
07:12:15       Mantid::Types::Core::DateAndTime::minimum() in
DateAndTime.cpp.o
07:12:15       Mantid::Types::Core::DateAndTime::operator-(long long)
const in DateAndTime.cpp.o
07:12:15
Mantid::Types::Core::DateAndTime::operator+(boost::posix_time::time_duration
const&) const in DateAndTime.cpp.o
07:12:15
Mantid::Types::Core::DateAndTime::operator-(boost::posix_time::time_duration
const&) const in DateAndTime.cpp.o
07:12:15       Mantid::Types::Core::DateAndTime::operator-(double) const
in DateAndTime.cpp.o
07:12:15   "Mantid::Types::Core::DateAndTime::MIN_NANOSECONDS",
referenced from:
07:12:15       Mantid::Types::Core::DateAndTime::maximum() in
DateAndTime.cpp.o
07:12:15       Mantid::Types::Core::DateAndTime::minimum() in
DateAndTime.cpp.o
07:12:15       Mantid::Types::Core::DateAndTime::operator-(long long)
const in DateAndTime.cpp.o
07:12:15
Mantid::Types::Core::DateAndTime::operator+(boost::posix_time::time_duration
const&) const in DateAndTime.cpp.o
07:12:15
Mantid::Types::Core::DateAndTime::operator-(boost::posix_time::time_duration
const&) const in DateAndTime.cpp.o
07:12:15       Mantid::Types::Core::DateAndTime::operator-(double) const
in DateAndTime.cpp.o
07:12:15 ld: symbol(s) not found for architecture x86_64
07:12:15 clang: error: linker command failed with exit code 1 (use -v to
see invocation)