Remove unused context variable in Sphinx categories processing
Jinja >= 2.11 now raises an error in some cases where context variables
are missing that appeared to be allowed before. The text_page context
entry was missing from the standard category.html raising an error:
  File /usr/lib/python3.6/site-packages/sphinx_bootstrap_theme/bootstrap/layout.html, line 24, in top-level template code
    {% if theme_bootstrap_version == 3 %}
  File /usr/lib/python3.6/site-packages/sphinx/themes/basic/layout.html, line 65, in top-level template code
    {#- old style sidebars: using blocks -- should be deprecated #}
  File /usr/lib/python3.6/site-packages/sphinx_bootstrap_theme/bootstrap/layout.html, line 47, in block content
    {%- endmacro %}
  File /home/builder/jenkins-linode/workspace/pull_requests-rhel7/docs/source/_templates/category.html, line 40, in block body
    {%- endfor -%}
  File /usr/lib/python3.6/site-packages/sphinx/jinja2glue.py, line 145, in get_source
    if template.startswith('!'):
jinja2.exceptions.UndefinedError: 'text_page' is undefined

The variable is a remnant leftover that is unused so it is removed